spring:
  application:
    name: config-server
  cloud:
    config:
      # label 分支
      label: master
      server:
        git:
          # uri git地址
          uri: https://github.com/Durianyang/springcloud-practice
          # searchPaths 表示目录
          searchPaths: repos
eureka:
  client:
    serviceUrl:
      defaultZone: http://47.93.11.144:8761/eureka/
